using System.ComponentModel.DataAnnotations;

namespace iSele.Models.Orders
{
    public class OrderMethodType
    {
        public int OrderMethodTypeID { get; set; }
        [StringLength(50)]
        [Display(Name = "Order Method Type")]
        public string MethodType { get; set; }
        [Display(Name = "Is generated by the system")]
        public bool? IsGenerated { get; set; }
    }
}